"""initial schema

Revision ID: c448a66d5401
Revises: 
Create Date: 2026-05-21 11:32:28.284480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c448a66d5401'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='sourcestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_project_id'), 'sources', ['project_id'], unique=False)
    op.create_table('source_fragments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('element_type', sa.Enum('HEADING', 'PARAGRAPH', 'LIST_ITEM', 'TABLE', 'CAPTION', 'IMAGE', 'FORMULA', 'REFERENCE', name='elementtype'), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.String(length=2048), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'position_index', name='uq_source_fragments_source_position')
    )
    op.create_index(op.f('ix_source_fragments_content_hash'), 'source_fragments', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_fragments_source_id'), 'source_fragments', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_fragments_source_id'), table_name='source_fragments')
    op.drop_index(op.f('ix_source_fragments_content_hash'), table_name='source_fragments')
    op.drop_table('source_fragments')
    op.drop_index(op.f('ix_sources_project_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('projects')
    sa.Enum(name='elementtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sourcestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
